"""Retail SPY limit-order and S&P 500 allocation research framework."""

from .backtest import BacktestConfig, BacktestResult, run_backtest, run_many
from .data import enrich_with_risk_free_rate, load_fred_risk_free_rate, load_shiller_data
from .daily_data import (
    DEFAULT_DAILY_START_DATE,
    DailyDataError,
    daily_data_summary,
    fetch_twelve_data_daily,
    load_daily_csv,
    load_or_fetch_twelve_data_daily,
    parse_twelve_data_daily,
    save_daily_csv,
)
from .limit_orders import evaluate_limit_discount_grid, one_session_limit_outcomes
from .limit_plotting import (
    calmar_by_discount_figure,
    drawdown_figure,
    strategy_calmar_ranking_figure,
    strategy_drawdown_figure,
    strategy_return_drawdown_figure,
    strategy_wealth_figure,
    return_drawdown_figure,
    walk_forward_calmar_figure,
    walk_forward_discount_figure,
    wealth_index_figure,
)
from .limit_portfolio import (
    RecurringLimitConfig,
    build_recurring_limit_equity_curve,
    compare_recurring_limit_strategies,
    evaluate_recurring_limit_grid,
    simulate_recurring_limit_strategy,
    summarize_recurring_limit_result,
    summarize_recurring_limit_risk,
    walk_forward_recurring_limit_selection,
)
from .risk_metrics import (
    annualized_compound_return,
    calmar_ratio,
    drawdown_series,
    maximum_drawdown,
    summarize_return_series,
    wealth_index_from_returns,
)
from .strategies import default_strategies, select_strategies, strategy_catalog

__all__ = [
    "BacktestConfig",
    "BacktestResult",
    "DEFAULT_DAILY_START_DATE",
    "DailyDataError",
    "RecurringLimitConfig",
    "annualized_compound_return",
    "build_recurring_limit_equity_curve",
    "calmar_by_discount_figure",
    "calmar_ratio",
    "compare_recurring_limit_strategies",
    "daily_data_summary",
    "default_strategies",
    "drawdown_figure",
    "drawdown_series",
    "enrich_with_risk_free_rate",
    "evaluate_limit_discount_grid",
    "evaluate_recurring_limit_grid",
    "fetch_twelve_data_daily",
    "load_daily_csv",
    "load_fred_risk_free_rate",
    "load_or_fetch_twelve_data_daily",
    "load_shiller_data",
    "maximum_drawdown",
    "one_session_limit_outcomes",
    "parse_twelve_data_daily",
    "return_drawdown_figure",
    "run_backtest",
    "run_many",
    "save_daily_csv",
    "select_strategies",
    "simulate_recurring_limit_strategy",
    "strategy_calmar_ranking_figure",
    "strategy_catalog",
    "strategy_drawdown_figure",
    "strategy_return_drawdown_figure",
    "strategy_wealth_figure",
    "summarize_recurring_limit_result",
    "summarize_recurring_limit_risk",
    "summarize_return_series",
    "walk_forward_calmar_figure",
    "walk_forward_discount_figure",
    "walk_forward_recurring_limit_selection",
    "wealth_index_figure",
    "wealth_index_from_returns",
]
